--
-- PostgreSQL database dump
--

restrict xhgMI2JhaJu3NUyBuPcYgbgcEoPmSr9v5zC2pEOApXw1bPXplpE7YRHfQrlYA90

-- Dumped from database version 13.22 (Debian 13.22-1.pgdg13+1)
-- Dumped by pg_dump version 13.22 (Debian 13.22-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: hospede; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hospede (
    id bigint NOT NULL,
    nome character varying(500) NOT NULL,
    documento character varying(255) NOT NULL,
    telefone character varying(255) NOT NULL
);


ALTER TABLE public.hospede OWNER TO postgres;

--
-- Name: hospede_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.hospede ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hospede_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: perfis; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.perfis (
    id bigint NOT NULL,
    nome character varying(255) NOT NULL
);


ALTER TABLE public.perfis OWNER TO postgres;

--
-- Name: perfis_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.perfis ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.perfis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reserva; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reserva (
    adicional_veiculo boolean NOT NULL,
    valor_total numeric(38,2),
    data_entrada timestamp(6) without time zone,
    data_saida timestamp(6) without time zone,
    hospede_id bigint,
    id bigint NOT NULL,
    status character varying(255),
    CONSTRAINT reserva_status_check CHECK (((status)::text = ANY ((ARRAY['CONFIRMADA'::character varying, 'PENDENTE'::character varying, 'CHECK_IN'::character varying, 'CHECK_OUT'::character varying, 'CANCELADA'::character varying])::text[])))
);


ALTER TABLE public.reserva OWNER TO postgres;

--
-- Name: reserva_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reserva ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reserva_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_perfis; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario_perfis (
    perfil_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);


ALTER TABLE public.usuario_perfis OWNER TO postgres;

--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    login character varying(255) NOT NULL,
    senha character varying(255) NOT NULL
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: hospede; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.hospede (id, nome, documento, telefone) FROM stdin;
\.


--
-- Data for Name: perfis; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.perfis (id, nome) FROM stdin;
1	ATENDENTE
\.


--
-- Data for Name: reserva; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reserva (adicional_veiculo, valor_total, data_entrada, data_saida, hospede_id, id, status) FROM stdin;
\.


--
-- Data for Name: usuario_perfis; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario_perfis (perfil_id, usuario_id) FROM stdin;
1	1
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios (id, login, senha) FROM stdin;
1	atendente	$2a$10$gNPz3Rm8VpJ9cRLH7OsMse7XCjzFBlngilhR724olle3Dg4q3m4PK
\.


--
-- Name: hospede_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hospede_id_seq', 1, false);


--
-- Name: perfis_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.perfis_id_seq', 1, true);


--
-- Name: reserva_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reserva_id_seq', 1, false);


--
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 1, true);


--
-- Name: hospede hospede_documento_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hospede
    ADD CONSTRAINT hospede_documento_key UNIQUE (documento);


--
-- Name: hospede hospede_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hospede
    ADD CONSTRAINT hospede_pkey PRIMARY KEY (id);


--
-- Name: perfis perfis_nome_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.perfis
    ADD CONSTRAINT perfis_nome_key UNIQUE (nome);


--
-- Name: perfis perfis_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.perfis
    ADD CONSTRAINT perfis_pkey PRIMARY KEY (id);


--
-- Name: reserva reserva_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reserva
    ADD CONSTRAINT reserva_pkey PRIMARY KEY (id);


--
-- Name: usuario_perfis usuario_perfis_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_perfis
    ADD CONSTRAINT usuario_perfis_pkey PRIMARY KEY (perfil_id, usuario_id);


--
-- Name: usuarios usuarios_login_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_login_key UNIQUE (login);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: usuario_perfis fk4fkjwdrgehlsu0tp9pfa4buhv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_perfis
    ADD CONSTRAINT fk4fkjwdrgehlsu0tp9pfa4buhv FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: usuario_perfis fkia0rv52k4ir0b4awrvbjpnh52; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_perfis
    ADD CONSTRAINT fkia0rv52k4ir0b4awrvbjpnh52 FOREIGN KEY (perfil_id) REFERENCES public.perfis(id);


--
-- Name: reserva fkj8ln3danf78mmxh5u29ex7m9u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reserva
    ADD CONSTRAINT fkj8ln3danf78mmxh5u29ex7m9u FOREIGN KEY (hospede_id) REFERENCES public.hospede(id);


--
-- PostgreSQL database dump complete
--

\unrestrict xhgMI2JhaJu3NUyBuPcYgbgcEoPmSr9v5zC2pEOApXw1bPXplpE7YRHfQrlYA90

